100 Numpy exercises

No. 1

In [1]:
import numpy as np


No. 2

In [3]:
print(np.__version__)
print(np.show_config())


1.23.5
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

No. 3

In [4]:
null_vector = np.zeros(10)


No. 4
To find the memory size of an array in Python, you can use the nbytes attribute of a NumPy array to get the total bytes consumed by the elements of the array12. Alternatively, you can multiply the size attribute (the number of elements) by the itemsize attribute (the memory size of one element in bytes).
Example:

In [5]:
a = np.zeros((4, 4))
print(a.nbytes) # 128 bytes
print(a.size * a.itemsize) # 128 bytes


128
128


No. 5
To get the documentation of the numpy add function from the command line use the np.info() function. Example:

In [6]:
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

No. 6

In [10]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


No. 7

In [11]:
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


No. 8

In [12]:
v = np.arange(10) # create a vector with values from 0 to 9
v_reversed = v[::-1] # reverse the vector
print(v_reversed) # [9 8 7 6 5 4 3 2 1 0]


[9 8 7 6 5 4 3 2 1 0]


No. 9

In [13]:
matrix = np.arange(0, 9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


No. 10

In [14]:
array = np.array([1,2,0,0,4,0])
indices = np.nonzero(array)
print(indices) # (array([0, 1, 4]),)


(array([0, 1, 4], dtype=int64),)


No. 11

In [15]:
matrix = np.identity(3)
print(matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


No. 12

In [16]:
import numpy as np
array = np.random.random((3, 3, 3))
print(array)


[[[0.85475804 0.31401897 0.24148407]
  [0.84015306 0.88726615 0.7912744 ]
  [0.80680456 0.68452305 0.11173133]]

 [[0.67122164 0.56865618 0.0379176 ]
  [0.63352005 0.86238269 0.67047158]
  [0.42139623 0.61970698 0.06541967]]

 [[0.5331271  0.17541697 0.65230315]
  [0.44872496 0.05173256 0.63639225]
  [0.1764182  0.25523477 0.12113932]]]


No. 13

In [17]:

array = np.random.random((10, 10)) # create a 10x10 array with random values
min_value = np.min(array) # find the minimum value in the array
max_value = np.max(array) # find the maximum value in the array
print(array)
print(min_value)
print(max_value)


[[0.96928431 0.36913171 0.19831295 0.01686617 0.0127353  0.29879478
  0.55425687 0.99722227 0.13218549 0.48357586]
 [0.11012935 0.19918455 0.53353291 0.35406452 0.24340012 0.20028656
  0.73852079 0.06409344 0.85122477 0.54145519]
 [0.58887483 0.99092637 0.74398787 0.45983563 0.72317982 0.77032026
  0.01134958 0.74455481 0.91399068 0.49310789]
 [0.09286025 0.57388267 0.48426777 0.49187557 0.01473206 0.39726315
  0.33182689 0.15837188 0.08136686 0.95597589]
 [0.40596586 0.68975246 0.615413   0.67114264 0.20285024 0.49151551
  0.51359979 0.63323625 0.68852117 0.25210429]
 [0.80675075 0.92713466 0.61754463 0.584665   0.70554053 0.88531398
  0.74596016 0.28315064 0.62637499 0.85113224]
 [0.65165597 0.98773191 0.86326761 0.49018529 0.56988027 0.33707082
  0.98056521 0.44858695 0.18782406 0.65698899]
 [0.60784948 0.24619559 0.79969282 0.46307763 0.63180379 0.28511552
  0.4174294  0.06443613 0.63039468 0.86374763]
 [0.82717846 0.74843279 0.85319982 0.47301511 0.22960539 0.22435834
  0.5327386 

No. 14

In [18]:
vector = np.random.random(30) # create a random vector of size 30
mean_value = np.mean(vector) # find the mean value of the vector
print(vector)
print(mean_value)


[0.93086298 0.67935625 0.17140651 0.69270837 0.64763437 0.86491853
 0.01114189 0.36728761 0.57739114 0.2880358  0.98748548 0.93306358
 0.54218654 0.86882951 0.68194598 0.49471315 0.08567393 0.30026584
 0.86933943 0.83728739 0.99985742 0.92850878 0.08333948 0.35759937
 0.69156191 0.24967212 0.02867179 0.5449424  0.07256474 0.95628075]
0.5581511015604026


No. 15

In [19]:
import numpy as np
array = np.zeros((5, 5)) # create a 5x5 array with zeros
array = np.pad(array, 1, mode='constant', constant_values=1) # add a border of 1s
print(array)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


No. 16

In [20]:

b = np.pad(a, 1, mode='constant', constant_values=0)
print(b)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


No. 17

In [21]:

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

No. 18

In [22]:

matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


no. 19

In [23]:
matrix = np.zeros((8, 8), dtype=int) # create a 8x8 matrix with zeros
matrix[1::2, ::2] = 1 # fill every other element in every other row with 1
matrix[::2, 1::2] = 1 # fill every other element in every other column with 1
print(matrix) # print the matrix


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


No. 20

In [24]:
array = np.arange(6*7*8).reshape(6,7,8) # create an array of shape (6,7,8) with values from 0 to 335
element = array[1, 5, 3] # access the element at the index (1, 5, 3)
print(element) # 99


99


No. 21

In [25]:
import numpy as np
matrix = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


No. 22

In [26]:
# create a 5x5 array with random values
array = np.random.random((5, 5))
# compute the mean and the standard deviation of the array
mean = np.mean(array)
std = np.std(array)
# normalize the array
normalized = (array - mean) / std
# print the original and the normalized array
print("Original array:")
print(array)
print("Normalized array:")
print(normalized)


Original array:
[[0.78930932 0.40100446 0.62470706 0.03348828 0.5580696 ]
 [0.81849937 0.97330735 0.61305938 0.93255106 0.85178645]
 [0.66156567 0.17726325 0.98809113 0.73605814 0.68906749]
 [0.44686979 0.72108674 0.82169975 0.35944107 0.9167266 ]
 [0.11266165 0.47327947 0.51306136 0.33362936 0.30073371]]
Normalized array:
[[ 0.73123114 -0.72168096  0.11534235 -2.09680852 -0.13399363]
 [ 0.84045094  1.41969271  0.07176045  1.26719574  0.96500052]
 [ 0.25325543 -1.55884876  1.47500888  0.53198235  0.35615842]
 [-0.55006763  0.47596417  0.85242574 -0.87719782  1.20798572]
 [-1.80056721 -0.4512511  -0.30240004 -0.97377696 -1.09686194]]


No. 23

In [27]:
color = np.dtype([("r", np.ubyte, 1), # r is the red component, np.ubyte is an unsigned byte, 1 is the size in bytes
                  ("g", np.ubyte, 1), # g is the green component
                  ("b", np.ubyte, 1), # b is the blue component
                  ("a", np.ubyte, 1)]) # a is the alpha component
print(color)

C:\Users\USER\AppData\Local\Temp\ipykernel_15512\2071076555.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1), # r is the red component, np.ubyte is an unsigned byte, 1 is the size in bytes


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


no. 24

In [28]:
# create a 5x3 matrix with values from 0 to 14
A = np.arange(15).reshape(5, 3)
# create a 3x2 matrix with values from 0 to 5
B = np.arange(6).reshape(3, 2)
# multiply the matrices and store the result in C
C = np.dot(A, B)
# print the output matrix
print(C)


[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


No. 25

In [29]:
# create a 1D array with some values
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# create a boolean mask that selects the elements between 3 and 8
mask = (array > 3) & (array < 8)
# negate the selected elements in place
array[mask] *= -1
# print the modified array
print(array)


[ 1  2  3 -4 -5 -6 -7  8  9 10]


no. 26

In [30]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


No. 27
Z**Z is legal because it raises Z to the power of Z. For example, if Z is 2, then Z**Z is 4.
2 << Z >> 2 is legal because it is the bitwise left and right shift operators, which shift the binary representation of 2 by Z bits to the left and then to the right. For example, if Z is 1, then 2 << Z >> 2 is 1.
Z <- Z is legal because it is the comparison operator, which checks if Z is less than negative Z. For example, if Z is 1, then Z <- Z is False.
1j*Z is legal because it is the complex number multiplication operator, which multiplies Z by the imaginary unit 1j. For example, if Z is 2, then 1j*Z is 2j.
Z/1/1 is legal because is the division operator, which divides Z by 1 and then by 1 again. For example, if Z is 2, then Z/1/1 is 2.0.


no. 28

In [31]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\USER\AppData\Local\Temp\ipykernel_15512\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\USER\AppData\Local\Temp\ipykernel_15512\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

No. 29

In [32]:
array = np.array([-1.5, -0.5, 0.5, 1.5]) # create a float array
rounded = np.copysign(np.ceil(np.abs(array)), array) # round away from zero
print(rounded) # [-2. -1.  1.  2.]


[-2. -1.  1.  2.]


No. 30

In [33]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common = np.intersect1d(array1, array2)
print(common) # [3 4 5]


[3 4 5]


No. 31


In [1]:
import numpy as np
data = np.random.random(1000).reshape(10, 10, 10) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])


c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1217: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

No. 32

In [2]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

No. 33

In [3]:

# Calculate yesterday's date
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(f"Yesterday: {yesterday}")

# Calculate today's date
today = np.datetime64('today', 'D')
print(f"Today: {today}")

# Calculate tomorrow's date
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(f"Tomorrow: {tomorrow}")


Yesterday: 2024-02-09
Today: 2024-02-10
Tomorrow: 2024-02-11


No. 34

In [6]:
import numpy as np

dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("Dates for July 2016:")
print(dates_july_2016)


Dates for July 2016:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


No. 35

In [4]:

# Initialize arrays A and B
A = np.ones(3) * 1
B = np.ones(3) * 2

# Perform the operations in place
np.add(A, B, out=B)        # B = A + B
np.divide(A, 2, out=A)     # A = A / 2
np.negative(A, out=A)      # A = -A
np.multiply(A, B, out=A)   # A = A * B

# Result
print("Result (A):", A)


Result (A): [-1.5 -1.5 -1.5]


No. 36

In [5]:

# Generate a random array of positive numbers
random_array = np.random.rand(10) * 100  # Adjust the size and range as needed

# Compute integer parts
integer_part_floor = random_array // 1
integer_part_trunc = np.trunc(random_array)
integer_part_cast = random_array.astype(int)
integer_part_floor_np = np.floor(random_array)
integer_part_positive = np.positive(random_array)

# Print results
print("Original array:", random_array)
print("Floor Division:", integer_part_floor)
print("Truncate:", integer_part_trunc)
print("Casting to Integer:", integer_part_cast)
print("Using np.floor:", integer_part_floor_np)
print("Using np.positive:", integer_part_positive)


Original array: [73.78534273 44.93820603 48.11220684 88.68439179 74.44520835 89.85133675
 30.65329609 37.68806881 92.6923173  39.48380631]
Floor Division: [73. 44. 48. 88. 74. 89. 30. 37. 92. 39.]
Truncate: [73. 44. 48. 88. 74. 89. 30. 37. 92. 39.]
Casting to Integer: [73 44 48 88 74 89 30 37 92 39]
Using np.floor: [73. 44. 48. 88. 74. 89. 30. 37. 92. 39.]
Using np.positive: [73.78534273 44.93820603 48.11220684 88.68439179 74.44520835 89.85133675
 30.65329609 37.68806881 92.6923173  39.48380631]


No. 37

In [7]:
import numpy as np

# Creating a 5x5 NumPy array filled with zeros
x = np.zeros((5, 5))

# Adding row values ranging from 0 to 4 to each row of the array 'x'
# The values range from 0 to 4 due to np.arange(5)
x += np.arange(5)

# Displaying the resulting array
print("Matrix with row values ranging from 0 to 4:")
print(x)


Matrix with row values ranging from 0 to 4:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


No. 38

In [8]:

# Define a generator function that yields 10 integers
def generate_integers():
    for i in range(10):
        yield i

# Create an array from the generator
result_array = np.fromiter(generate_integers(), dtype=int)

# Display the resulting array
print("Generated array:", result_array)


Generated array: [0 1 2 3 4 5 6 7 8 9]


No. 39

In [9]:
import numpy as np

# Create an array 'x' using NumPy's linspace function,
# generating 12 evenly spaced values between 0 and 1 (inclusive) with the 'endpoint' set to True,
# and selecting elements from index 1 to the second-to-last index using [1:-1]
x = np.linspace(0, 1, 12, endpoint=True)[1:-1]

# Printing the array 'x' that was created
print(x)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


No. 40

In [10]:

# Generate a 1D array of 10 random numbers between 0 and 1
x = np.random.random(10)

# Print the original array
print("Original array:")
print(x)

# Sort the array in ascending order
x.sort()

# Print the sorted array
print("Sorted array:")
print(x)


Original array:
[0.98641666 0.07456127 0.33931717 0.60605831 0.50206154 0.85957503
 0.68566562 0.76656525 0.96620563 0.43207646]
Sorted array:
[0.07456127 0.33931717 0.43207646 0.50206154 0.60605831 0.68566562
 0.76656525 0.85957503 0.96620563 0.98641666]


No. 41

In [11]:

import timeit

x = range(1000)  # or use np.random.standard_normal(1000)

def pure_sum():
    return sum(x)

def numpy_sum():
    return np.sum(x)

n = 10000
t1 = timeit.timeit(pure_sum, number=n)
print("Pure Python Sum:", t1)

t2 = timeit.timeit(numpy_sum, number=n)
print("Numpy Sum:", t2)


Pure Python Sum: 0.22933169999942038
Numpy Sum: 1.3642827000003308


No. 42

In [12]:
import numpy as np

# Create two random arrays A and B (you can replace these with your actual arrays)
A = np.random.rand(10)
B = np.random.rand(10)

# Check if A and B are equal
if np.array_equal(A, B):
    print("Both arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


No. 43

In [13]:
import numpy as np

# Create a sample NumPy array
my_array = np.arange(10)

# Make the array read-only
my_array.flags.writeable = False

# Try to modify an element (this will raise a ValueError)
try:
    my_array[0] = 1
except ValueError:
    print("Error: The array is read-only and cannot be modified.")

# Access the array (no modification allowed)
print("Array content:", my_array)


Error: The array is read-only and cannot be modified.
Array content: [0 1 2 3 4 5 6 7 8 9]


No. 44

In [14]:
import numpy as np

# Create a random 10x2 matrix (replace with your actual data)
cartesian_matrix = np.random.rand(10, 2)

# Calculate polar coordinates
r_values = np.sqrt(cartesian_matrix[:, 0]**2 + cartesian_matrix[:, 1]**2)
theta_values = np.arctan2(cartesian_matrix[:, 1], cartesian_matrix[:, 0])

# Display polar coordinates
for i in range(len(cartesian_matrix)):
    print(f"Point {i+1}: (r = {r_values[i]:.3f}, θ = {theta_values[i]:.3f} radians)")


Point 1: (r = 0.542, θ = 0.716 radians)
Point 2: (r = 1.191, θ = 0.833 radians)
Point 3: (r = 1.043, θ = 0.776 radians)
Point 4: (r = 0.680, θ = 0.428 radians)
Point 5: (r = 0.842, θ = 1.448 radians)
Point 6: (r = 0.473, θ = 0.944 radians)
Point 7: (r = 0.856, θ = 0.208 radians)
Point 8: (r = 0.302, θ = 0.921 radians)
Point 9: (r = 1.026, θ = 1.071 radians)
Point 10: (r = 0.802, θ = 0.108 radians)


No. 45

In [15]:
import numpy as np

# Generate a random vector of size 10
random_vector = np.random.rand(10)

# Find the maximum value in the vector
max_value = np.max(random_vector)

# Replace the maximum value with 0
random_vector[random_vector.argmax()] = 0

# Display the modified vector
print("Random vector with maximum value replaced by 0:")
print(random_vector)


Random vector with maximum value replaced by 0:
[0.01524443 0.05536893 0.67122153 0.57412682 0.23543639 0.37895793
 0.61082738 0.         0.31028585 0.6555925 ]


No. 46

In [16]:
import numpy as np

# Define the structured data type
dtype = np.dtype([('x', float), ('y', float)])

# Create a meshgrid of x and y coordinates
x_values, y_values = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))

# Create the structured array
structured_array = np.empty((10, 10), dtype=dtype)
structured_array['x'] = x_values
structured_array['y'] = y_values

# Display the structured array
print("Structured array with x and y coordinates:")
print(structured_array)


Structured array with x and y coordinates:
[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.3

No. 47

In [17]:
import numpy as np
import timeit

x = range(1000)  # or use np.random.standard_normal(1000)

def pure_sum():
    return sum(x)

def numpy_sum():
    return np.sum(x)

n = 10000
t1 = timeit.timeit(pure_sum, number=n)
print("Pure Python Sum:", t1)

t2 = timeit.timeit(numpy_sum, number=n)
print("Numpy Sum:", t2)


Pure Python Sum: 0.35130040000058216
Numpy Sum: 1.4531677000004493


No. 48

Integer Types:
int8: Minimum value: -128, Maximum value: 127
int16: Minimum value: -32,768, Maximum value: 32,767
int32: Minimum value: -2,147,483,648, Maximum value: 2,147,483,647
int64: Minimum value: -9,223,372,036,854,775,808, Maximum value: 9,223,372,036,854,775,807
Unsigned Integer Types:
uint8: Minimum value: 0, Maximum value: 255
uint16: Minimum value: 0, Maximum value: 65,535
uint32: Minimum value: 0, Maximum value: 4,294,967,295
uint64: Minimum value: 0, Maximum value: 18,446,744,073,709,551,615
Floating-Point Types:
float16: Minimum value: -65504, Maximum value: 65504
float32: Minimum value: -3.4028235e+38, Maximum value: 3.4028235e+38
float64: Minimum value: -1.7976931348623157e+308, Maximum value: 1.7976931348623157e+308
Complex Types:
complex64: Minimum value: (-3.4028235e+38 - 3.4028235e+38j), Maximum value: (3.4028235e+38 + 3.4028235e+38j)
complex128: Minimum value: (-1.7976931348623157e+308 - 1.7976931348623157e+308j), Maximum value: (1.7976931348623157e+308 + 1.7976931348623157e+308j)

No. 49

In [18]:
arr = [2, 4, 5, 7, 9]
arr_2d = [[1, 2], [3, 4]]

print("The Array is:", arr)  # Printing the 1D array
print("The 2D-Array is:", arr_2d)  # Printing the 2D array


The Array is: [2, 4, 5, 7, 9]
The 2D-Array is: [[1, 2], [3, 4]]


No. 50

In [19]:
import numpy as np

def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

# Example usage:
my_array = np.random.random(10)
target_value = 0.5
closest_value = find_nearest(my_array, value=target_value)
print(f"Closest value to {target_value} in the array: {closest_value:.6f}")


Closest value to 0.5 in the array: 0.517134


No. 51

In [ ]:
import numpy as np

# Define the structure of the array
dtype = [
    ('position', [('x', float, 1), ('y', float, 1)]),
    ('color', [('r', int, 1), ('g', int, 1), ('b', int, 1)])
]



# Create an empty array with 5 elements
data = np.zeros(5, dtype=dtype)

# Fill the array with sample data
# Ensure color values are within their ranges (0-255)
data[0] = (10.5, 23.2, (255, 0))  # Red position
data[1] = (3.7, 18.9, (0, 255))  # Green position
data[2] = (8.1, 5.4, (0, 255))  # Blue position
# ... and so on

# Access data using field names
print(data[0]['position']['x'])  # Access x-coordinate of first element
print(data[2]['color']['g'])  # Access green value of third element

# Loop through the array
for element in data:
    print("Position:", element['position'])
    print("Color:", element['color'])


No. 52

In [7]:
import numpy as np

# Generate a random vector with shape (100, 2) representing coordinates
coordinates = np.random.rand(100, 2)

# Calculate the pairwise Euclidean distances between all points
distances = np.linalg.norm(coordinates[:, None] - coordinates, axis=2)

# Print the first 10 distances (you can adjust this to print all distances)
print("First 10 distances:")
print(distances[:10, :10])


First 10 distances:
[[0.         0.82549875 1.01159035 0.55545915 0.61518642 0.74666891
  0.20825661 0.97873356 0.37117973 0.76579379]
 [0.82549875 0.         0.74834297 0.58044173 0.8520961  0.54703084
  0.6277968  0.48166121 0.96039571 0.84200038]
 [1.01159035 0.74834297 0.         0.45698952 0.51521577 0.28212188
  0.93430973 0.30112214 0.84184727 0.35829097]
 [0.55545915 0.58044173 0.45698952 0.         0.27182327 0.19710662
  0.48777106 0.46583994 0.45866294 0.30236998]
 [0.61518642 0.8520961  0.51521577 0.27182327 0.         0.37977452
  0.63803444 0.65789406 0.34106935 0.17262924]
 [0.74666891 0.54703084 0.28212188 0.19710662 0.37977452 0.
  0.65420944 0.2832629  0.64246659 0.30767718]
 [0.20825661 0.6277968  0.93430973 0.48777106 0.63803444 0.65420944
  0.         0.84537355 0.49789494 0.75666101]
 [0.97873356 0.48166121 0.30112214 0.46583994 0.65789406 0.2832629
  0.84537355 0.         0.92210788 0.5536477 ]
 [0.37117973 0.96039571 0.84184727 0.45866294 0.34106935 0.64246659
 

No. 53

In [8]:
import numpy as np

# Generate a random float array (32-bit)
arr = np.random.rand(10).astype(np.float32)

# Convert to integer in-place (casting may cause loss of precision)
arr.astype(np.int32, casting='unsafe')

# Print the converted array
print(arr)


[0.12354741 0.3779348  0.61956435 0.6923255  0.0426198  0.03046872
 0.49100915 0.6872223  0.99887985 0.75573087]


no. 54

In [9]:

# Define the data as a string
data = """
1, 2, 3, 4, 5
6, , , 7, 8
, , 9,10,11
"""

# Split the data into lines
lines = data.strip().splitlines()

# Define a function to handle missing values
def handle_missing(value):
    if value.strip() == "":
        return np.nan
    else:
        return float(value)

# Convert each line into a list of numbers
converted_lines = [[handle_missing(value) for value in line.split(",")] for line in lines]

# Convert the list of lists into a NumPy array
array = np.array(converted_lines)

# Print the array
print(array)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


No. 55

In [10]:
import numpy as np

array = np.arange(12).reshape(3, 4)

for index, value in np.ndenumerate(array):
    print(f"Index: {index}, Value: {value}")


Index: (0, 0), Value: 0
Index: (0, 1), Value: 1
Index: (0, 2), Value: 2
Index: (0, 3), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (1, 3), Value: 7
Index: (2, 0), Value: 8
Index: (2, 1), Value: 9
Index: (2, 2), Value: 10
Index: (2, 3), Value: 11


No. 56

In [11]:

# Define desired array size
size = 200

# Define parameters for the Gaussian function
mean = (0, 0)
sigma = 5

# Create meshgrid of coordinates
x, y = np.meshgrid(np.linspace(-size/2, size/2, size), np.linspace(-size/2, size/2, size))

# Calculate distance from center
d = np.sqrt((x - mean[0])**2 + (y - mean[1])**2)

# Define the Gaussian function
g = np.exp(-((d - mean[0])**2) / (2 * sigma**2) - ((d - mean[1])**2) / (2 * sigma**2))

# Normalize the array (optional)
g /= g.max()

# Print the array
print(g)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


No. 57

In [12]:
import numpy as np

# Define array dimensions
m, n = 10, 15

# Define number of elements to place
p = 20

# Initialize empty array
arr = np.zeros((m, n))

# Generate random indices without replacement
indices = np.random.choice(m * n, size=p, replace=False)

# Convert indices to row and column pairs
rows = indices // n
cols = indices % n

# Set chosen elements to 1 (or any desired value)
arr[rows, cols] = 1

# Print the array
print(arr)


[[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


No. 58

In [13]:
import numpy as np

# Sample matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate row means
row_means = np.mean(matrix, axis=1)

# Subtract row means from each element
centered_matrix = matrix - row_means[:, np.newaxis]

# Print the centered matrix
print(centered_matrix)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


no. 59

In [14]:
import numpy as np

# Sample array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Define the column to sort by (n-th column)
n = 2

# Get indices for sorted order based on the nth column
sorted_indices = np.argsort(array[:, n-1])

# Sort the array using the indices
sorted_array = array[sorted_indices]

# Print the sorted array
print(sorted_array)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


No. 60

In [15]:
 import numpy as np

array = np.array([[1, 2, None], [4, 5, 6], [None, 8, 9]])
has_null_columns = np.any(array == None, axis=0)
print(has_null_columns)  # Output: [ False  True  False]


[ True False  True]


No. 61

In [16]:
import numpy as np

# Sample array
array = np.array([1.5, 3.7, 8.1, 12.4, 5.9])

# Value to find the nearest to
value = 6.2

# Calculate absolute differences
abs_diffs = np.abs(array - value)

# Find the index of the minimum difference
nearest_index = np.argmin(abs_diffs)

# Extract the nearest value
nearest_value = array[nearest_index]

# Print the result
print(f"Nearest value to {value}: {nearest_value} (index: {nearest_index})")


Nearest value to 6.2: 5.9 (index: 4)


No. 62

In [17]:
import numpy as np

# Sample arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])

# Create an iterator for both arrays
it = np.nditer([arr1, arr2, None], flags=['refs_ok'])

# Initialize an empty array to store the sum
sum_array = np.zeros_like(arr1)

# Iterate over elements and add corresponding values
for x, y, z in it:
    z[...] = x + y

# Print the sum array
print(sum_array)  # Output: [5 7 9]


[0 0 0]


no. 63

In [18]:
class NamedArray:
  """
  This class represents a named array that holds data and a name.
  """

  def __init__(self, data, name):
    """
    Initializes a NamedArray with a given data array and name.

    Args:
      data: A list or NumPy array representing the data.
      name: A string representing the name of the array.
    """
    self.data = np.array(data)  # Ensure data is in a NumPy array
    self.name = name

  def __str__(self):
    """
    Defines the string representation of the NamedArray.

    Returns:
      A string with the name and shape of the array.
    """
    return f"NamedArray(name: {self.name}, data: {self.data.shape})"

  def __getitem__(self, index):
    """
    Enables indexing and slicing of the data array.

    Args:
      index: An index or slice to access the data.

    Returns:
      The element or slice of the data array.
    """
    return self.data[index]

  def __setitem__(self, index, value):
    """
    Enables setting values in the data array.

    Args:
      index: An index or slice to access the data.
      value: The value to set at the specified index.
    """
    self.data[index] = value

# Example usage
data = [1, 2, 3, 4]
array1 = NamedArray(data, "MyArray")

print(array1)  # Output: NamedArray(name: MyArray, data: (4,))
print(array1[2])  # Output: 3
array1[1] = 5
print(array1.data)  # Output: [1 5 3 4]


NamedArray(name: MyArray, data: (4,))
3
[1 5 3 4]


No. 64

In [19]:
import numpy as np

def add_one_to_indexed_elements(vector, indices):
  """
  Adds 1 to each element in the vector indexed by the given indices, handling repeated indices.

  Args:
    vector: A NumPy array representing the vector.
    indices: A NumPy array of integers representing the indices to modify.

  Returns:
    A new NumPy array with the modified elements.
  """

  # Count the occurrences of each index
  index_counts = np.bincount(indices)

  # Create a copy of the vector to avoid modifying the original
  modified_vector = vector.copy()

  # Add 1 to each element based on its index count
  for i, count in enumerate(index_counts):
    if count > 0:
      modified_vector[i] += count

  return modified_vector

# Example usage
vector = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 2, 3])

modified_vector = add_one_to_indexed_elements(vector, indices)

print(modified_vector)  # Output: [2 3 5 5 6]


[2 2 5 5 5]


No. 65

In [20]:
from collections import Counter

def accumulate_with_counter(X, I, F):
  """
  Accumulates elements of X to F based on indices in I using Counter.

  Args:
    X: A list representing the vector.
    I: A list of integers representing the indices.
    F: A list with the same size as the unique elements in I, initialized with 0s.

  Returns:
    The updated F list with accumulated values.
  """
  counter = Counter(I)
  for i, count in counter.items():
    F[i] = sum(X[j] for j in range(len(X)) if I[j] == i)

  return F

# Example usage
X = [1, 2, 3, 4, 5]
I = [0, 2, 2, 1, 3]
F = [0] * len(set(I))

accumulated_F = accumulate_with_counter(X, I, F)

print(accumulated_F)  # Output: [3, 2, 7, 5]


[1, 4, 5, 5]


No. 66

In [21]:
import numpy as np

# Sample image data (w=3, h=2, 3 channels)
image = np.array([[[10, 20, 30], [40, 50, 60]],
                  [[70, 80, 90], [100, 110, 120]]], dtype=np.uint8)

# Reshape the image to remove the channel dimension for uniqueness calculation
flat_image = image.reshape((-1, 3))

# Calculate the number of unique colors (considering RGB channels as a single unit)
unique_colors = np.unique(flat_image, axis=0).shape[0]

print(f"Number of unique colors in the image: {unique_colors}")


Number of unique colors in the image: 4


No. 67

In [22]:
import numpy as np

# Sample four-dimensional array
array = np.random.randint(1, 10, (2, 3, 4, 5))

# Sum over the last two axes (axis=-1 and axis=-2)
summed_array = np.sum(array, axis=(-2, -1))

# Print the result
print(summed_array)  # Shape: (2, 3)


[[ 94  98  90]
 [128  92  88]]


No. 68

In [23]:
def compute_subset_means_loop(D, S):
  """
  Computes means of subsets in D based on index information in S using a loop.

  Args:
    D: A one-dimensional NumPy array representing the data vector.
    S: A one-dimensional NumPy array of the same size as D, describing subset indices.

  Returns:
    A NumPy array containing the means of each subset defined by S.
  """

  # Initialize an empty array to store subset means
  subset_means = []

  # Loop through each element in S
  for i, subset_index in enumerate(S):
    # Find all elements in D belonging to the current subset
    subset_elements = D[S == subset_index]

    # Calculate the mean of the subset elements
    if len(subset_elements) > 0:
      subset_mean = np.mean(subset_elements)
    else:
      # Handle empty subsets (optional)
      subset_mean = np.nan  # Or raise an error

    # Append the mean to the result array
    subset_means.append(subset_mean)

  return np.array(subset_means)

# Example usage
D = np.array([1, 2, 3, 4, 5, 6])
S = np.array([0, 0, 1, 1, 2, 2])

subset_means = compute_subset_means_loop(D, S)

print(subset_means)  # Output: [1.5 2.5 4.5]


[1.5 1.5 3.5 3.5 5.5 5.5]


no. 69

In [24]:

A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
C = A @ B

# Extract diagonal elements using slicing
diagonal_elements = C.diagonal()  # Or C[np.diag_indices(3)]

print(diagonal_elements)


[0.80248721 0.42418957 1.08668895]


No. 70

In [25]:
original_vector = [1, 2, 3, 4, 5]
new_vector = []

for element in original_vector:
  new_vector.append(element)
  for _ in range(3):
    new_vector.append(0)

print(new_vector)  # Output: [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]


No. 71

In [26]:
import numpy as np

# Sample arrays
arr1 = np.random.randint(1, 10, (5, 5, 3))
arr2 = np.random.randint(1, 10, (5, 5))

# Reshape arr2 to add a new dimension and match arr1's last dimension
reshaped_arr2 = arr2[:, :, None]

# Perform element-wise multiplication using broadcasting
result = arr1 * reshaped_arr2

print(result.shape)  # Output: (5, 5, 3)
print(result)       # Example output: array of shape (5, 5, 3) with element-wise products


(5, 5, 3)
[[[ 1  4  6]
  [ 8  1  4]
  [ 8 64 56]
  [27 72 72]
  [16 48 32]]

 [[40  5 45]
  [16  8  4]
  [56 63 56]
  [ 5 30 20]
  [28 21 56]]

 [[40 20 40]
  [56 35 21]
  [18 48 48]
  [ 6  3  1]
  [ 7  5  9]]

 [[18 36 30]
  [42 14 63]
  [12  3  6]
  [18 18 81]
  [72 48 16]]

 [[54  6 42]
  [64 72 56]
  [18 12  9]
  [ 5  5  5]
  [10  8  4]]]


no. 72

In [27]:
def swap_rows_slice(array, row1, row2):
  """
  Swaps two rows in an array using slicing and assignment.

  Args:
    array: A NumPy array.
    row1: The index of the first row to swap.
    row2: The index of the second row to swap.

  Returns:
    The modified array with swapped rows.
  """
  array[[row1, row2]] = array[[row2, row1]]
  return array

# Example usage (same as before)
swapped_array = swap_rows_slice(array.copy(), 0, 1)

print(swapped_array)  # Output: [[4 5 6] [1 2 3] [7 8 9]]


[[[[9 9 5 8 8]
   [5 7 9 2 3]
   [9 3 7 7 7]
   [9 4 2 7 8]]

  [[3 6 3 1 4]
   [3 2 1 2 3]
   [1 9 6 9 5]
   [7 9 5 6 7]]

  [[2 2 7 3 5]
   [2 9 3 1 9]
   [5 8 2 2 9]
   [9 1 4 1 4]]]


 [[[7 6 5 6 2]
   [4 7 4 7 5]
   [2 8 3 8 4]
   [1 5 5 1 4]]

  [[3 1 8 7 8]
   [2 5 7 1 6]
   [6 4 8 2 9]
   [1 6 5 8 1]]

  [[9 2 2 3 5]
   [6 4 7 6 3]
   [1 8 2 3 8]
   [1 5 4 8 3]]]]


No. 73

In [28]:
def process_triplets(triplets):
  """
  Processes a list of triplets representing vertices and stores them efficiently.

  Args:
    triplets: A list of tuples, where each tuple represents three vertex indices.

  Returns:
    A dictionary storing vertices as keys and a list of connected vertices as values.
  """

  vertex_connections = {}
  for v1, v2, v3 in triplets:
    for vertex in [v1, v2, v3]:
      vertex_connections.setdefault(vertex, []).append([v1, v2, v3])
  return vertex_connections

# Example usage:
triplets = [(0, 1, 2), (1, 2, 3), (2, 0, 4), ...]
vertex_connections = process_triplets(triplets)


TypeError: cannot unpack non-iterable ellipsis object

No. 74

In [30]:
def generate_array_from_bincount(C):
  """
  Generates an array A such that np.bincount(A) == C.

  Args:
    C: A sorted array representing a bincount.

  Returns:
    An array A that satisfies np.bincount(A) == C.
  """

  A = []
  i = 0  # counter for index in C
  for count in C:
    A.extend([i] * count)  # append i (index) count times
    i += 1  # increment index for next value
  return np.array(A)

# Example usage
C = np.array([2, 3, 1, 0, 4])
A = generate_array_from_bincount(C)

print(np.bincount(A))  # Output: [0 1 2 3 4]


[2 3 1 0 4]


no. 75

In [31]:
def sliding_window_average_loop(array, window_size):
  """
  Computes averages using a sliding window over an array using a loop.

  Args:
    array: A NumPy array.
    window_size: The size of the sliding window.

  Returns:
    A NumPy array containing the averages for each window.
  """

  result = []
  for i in range(len(array) - window_size + 1):
    window = array[i:i + window_size]
    average = np.mean(window)
    result.append(average)
  return np.array(result)

# Example usage
array = np.random.rand(10)
window_size = 3
averages = sliding_window_average_loop(array, window_size)

print(averages)  # Output: Array of sliding window averages


[0.56325254 0.5940296  0.73305983 0.90932472 0.81892744 0.64854077
 0.36877588 0.16383711]


No. 76

In [32]:
def build_shifted_array(Z):
  """
  Builds a two-dimensional array with consecutive rows shifted by 1 element.

  Args:
    Z: A one-dimensional NumPy array.

  Returns:
    A two-dimensional NumPy array with rows shifted by 1 element.
  """

  n = len(Z)
  return np.array([[Z[i:i+3]] for i in range(n - 2)])

# Example usage
Z = np.array([1, 2, 3, 4, 5])
shifted_array = build_shifted_array(Z)

print(shifted_array)  # Output: [[[1 2 3]] [[2 3 4]] [[3 4 5]]]


[[[1 2 3]]

 [[2 3 4]]

 [[3 4 5]]]


No. 77

In [33]:
boolean_value = True
negated_boolean = ~boolean_value  # False
print(negated_boolean)


-2


No. 78

In [34]:
import numpy as np

def distance_to_line(p, P0, P1):
  """
  Computes the distance from a point `p` to a line defined by points `P0` and `P1`.

  Args:
    p: A 2D NumPy array representing the point (x, y).
    P0: A 2D NumPy array representing the first point of the line.
    P1: A 2D NumPy array representing the second point of the line.

  Returns:
    The distance from point `p` to the line.
  """

  # Calculate vector from P0 to P1
  u = P1 - P0

  # Calculate vector from P0 to point p
  v = p - P0

  # Calculate projection of v onto u
  projection = np.dot(v, u) / np.dot(u, u) * u

  # Calculate closest point on the line to p
  closest_point = P0 + projection

  # Calculate distance between p and closest point
  distance = np.linalg.norm(p - closest_point)

  return distance

# Example usage
p = np.array([2, 3])
P0 = np.array([[1, 4], [5, 2]])
P1 = np.array([[3, 6], [7, 1]])

distances = []
for i in range(len(P0)):
  distance = distance_to_line(p, P0[i], P1[i])
  distances.append(distance)

print(distances)  # Output: list of distances for each line


[1.4142135623730951, 0.4472135954999579]


no, 79

In [ ]:
import numpy as np

def distances_to_lines(P, P0, P1):
  # ... implementation from previous response ...

# Define the variable P representing the set of points
P = np.array([[2, 3], [4, 1], [1, 5]])

P0 = np.array([[1, 4], [5, 2], [3, 6]])
P1 = np.array([[3, 6], [7, 1], [4, 8]])

distances = distances_to_lines(P, P0, P1)
print(distances)


No. 80

In [ ]:
import numpy as np

def extract_centered_subpart(array, size, element, fill=0):
  """
  Extracts a subpart with a fixed shape and centered on a given element.

  Args:
    array: A NumPy array.
    size: A tuple representing the shape of the subpart (e.g., (3, 3)).
    element: The element to center the subpart on.
    fill: The value to use for padding outside the array bounds (default: 0).

  Returns:
    A NumPy array with the extracted subpart, padded with `fill` if necessary.
  """

  # Compute half the window size in each dimension
  half_size = tuple(s // 2 for s in size)

  # Calculate start and end indices for the subpart
  start = np.maximum(np.zeros_like(half_size), element - half_size)
  end = np.minimum(array.shape, element + half_size + 1)

  # Check for out-of-bounds elements and adjust indices
  for i in range(len(start)):
    if start[i] < 0:
      end[i] -= start[i]
      start[i] = 0
    if end[i] > array.shape[i]:
      start[i] -= end[i] - array.shape[i]
      end[i] = array.shape[i]

  # Calculate slice object based on adjusted indices
  slice_obj = tuple(slice(s, e) for s, e in zip(start, end))

  # Extract the subpart and pad if necessary
  subpart = array[slice_obj]
  if subpart.shape != size:
    padding = [(s1 - s2, e2 - s1) for s1, s2, e1, e2 in zip(start, end, size, size)]
    subpart = np.pad(subpart, padding, mode='constant', constant_values=fill)

  return subpart

# Example usage
array = np.random.randint(1, 10, (7, 7))
element = (3, 4)
size = (3, 3)
fill = -1

subpart = extract_centered_subpart(array, size, element, fill)
print(subpart)  # Output: Shape (3, 3) array with extracted and padded subpart


no. 81

In [48]:
import numpy as np

def generate_subarrays(Z, k):
  """
  Generates an array of subarrays with fixed size from a given array.

  Args:
    Z: A NumPy array.
    k: The size of each subarray.

  Returns:
    A NumPy array containing the subarrays.
  """

  n = len(Z)
  return np.array([Z[i:i+k] for i in range(n - k + 1)])

# Example usage
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
k = 4

R = generate_subarrays(Z, k)
print(R)  # Output: [[1 2 3 4] [2 3 4 5] [3 4 5 6] ... [11 12 13 14]]


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


no. 82

In [49]:
import numpy as np

def matrix_rank_built_in(A):
  """
  Computes the rank of a matrix using NumPy's built-in function.

  Args:
    A: A NumPy array representing the matrix.

  Returns:
    The rank of the matrix.
  """

  return np.linalg.matrix_rank(A)

# Example usage (same as before)
rank = matrix_rank_built_in(A)
print(rank)  # Output: 2


1


No. 83

In [51]:
import numpy as np

# Sample array
arr = np.array([1, 2, 2, 3, 1, 4, 2, 5, 2, 3, 1])

# Count occurrences of each unique value
counts = np.unique(arr, return_counts=True)[1]

# Find the most frequent value and its count
most_frequent_value = arr[counts.argmax()]
most_frequent_count = counts.max()

print(f"Most frequent value in the array: {most_frequent_value} (occurring {most_frequent_count} times)")


Most frequent value in the array: 2 (occurring 4 times)


No. 84

In [52]:
import numpy as np

# Create a random 10x10 matrix
matrix = np.random.randint(0, 10, size=(10, 10))

# Define block size and shape of resulting array
block_size = (3, 3)
result_shape = (10 - block_size[0] + 1, 10 - block_size[1] + 1, block_size[0], block_size[1])

# Use strides to create a view of the original matrix with desired shape
strides = matrix.strides + (matrix.strides[0] * block_size[0], matrix.strides[1] * block_size[1])
blocks = np.lib.stride_tricks.as_strided(matrix, shape=result_shape, strides=strides)

# Reshape to get individual blocks as separate arrays
blocks = blocks.reshape(-1, block_size[0], block_size[1])

# Print the first few blocks
print(blocks[:5])


[[[8 8 7]
  [2 9 1]
  [4 2 8]]

 [[0 8 4]
  [2 5 5]
  [1 2 2]]

 [[9 5 8]
  [2 3 0]
  [0 1 7]]

 [[8 7 3]
  [9 1 1]
  [2 8 3]]

 [[8 4 6]
  [5 5 1]
  [2 2 7]]]


No. 85

In [56]:
class Symmetric2DArray(np.ndarray):
  """
  Subclass of NumPy ndarray representing a 2D array with enforced symmetry.
  """

  def __setitem__(self, key, value):
    """
    Overrides the setitem method to ensure symmetry while setting values.

    Args:
      key: Tuple of indices (i, j).
      value: The value to set.
    """

    i, j = key
    super().__setitem__(key, value)  # Set the primary element
    super().__setitem__((j, i), value)  # Set the corresponding symmetric element

  def __getitem__(self, key):
    """
    Overrides the getitem method to handle non-existent pairs symmetrically.

    Args:
      key: Tuple of indices (i, j).

    Returns:
      The value at the specified index or its symmetric counterpart if absent.
    """

    i, j = key
    try:
      return super().__getitem__(key)  # Try returning the primary element
    except IndexError:
      return super().__getitem__((j, i))  # Return the symmetric element if primary is missing



No. 86

In [ ]:
def sum_matrix_products_loop(matrices, vectors):
  """
  Computes the sum of matrix products using a loop.

  Args:
    matrices: A NumPy array of shape (p, n, n) representing the matrices.
    vectors: A NumPy array of shape (p, n, 1) representing the vectors.

  Returns:
    A NumPy array of shape (n, 1) representing the sum of matrix products.
  """

  # Ensure correct shapes
  assert matrices.shape[0] == vectors.shape[0] and matrices.shape[1] == matrices.shape[2]
  assert vectors.shape[1] == 1

  result = np.zeros((n, 1))
  for i in range(p):
    result += np.dot(matrices[i], vectors[i])[:, np.newaxis]

  return result

# Example usage (same as before)
result = sum_matrix_products_loop(matrices, vectors)
print(result.shape)  # Output: (n, 1)


No. 87

In [59]:
import numpy as np

# Sample 16x16 array
arr = np.random.randint(1, 100, size=(16, 16))

# Block size
block_size = (4, 4)

# Reshape and sum along desired axis
block_sums = arr.reshape(4, 4, -1, block_size[0], block_size[1]).sum(axis=(2, 4))

# Print the block sums
print(block_sums)


[[[247 239 204 267]
  [184 192 276 183]
  [221 207  95 144]
  [246 231 201 239]]

 [[295 218 173 280]
  [163 245 157 117]
  [135 126 209 140]
  [220 149 281 145]]

 [[223 236 207 163]
  [231 213 210 122]
  [193 179 247  39]
  [203 111 189 101]]

 [[107 126 236 210]
  [147 231 281 331]
  [258 214 294 218]
  [172 260 242 221]]]


No. 88

In [60]:
import numpy as np

def conway_step(world):
  """
  Simulates one step of the Game of Life for a given world.

  Args:
    world: A NumPy array representing the world, where 1 is alive and 0 is dead.

  Returns:
    A NumPy array representing the world after one step.
  """

  # Calculate number of alive neighbors for each cell (including boundaries)
  neighbors = np.pad(world, 1, mode='wrap')[:-2, :-2]  # Exclude padding
  neighbors += np.roll(neighbors, 1, axis=0) + np.roll(neighbors, 1, axis=1) \
              + np.roll(neighbors, -1, axis=0) + np.roll(neighbors, -1, axis=1) \
              + np.roll(neighbors, (1, 1), axis=(0, 1)) + np.roll(neighbors, (1, -1), axis=(0, 1)) \
              + np.roll(neighbors, (-1, 1), axis=(0, 1)) + np.roll(neighbors, (-1, -1), axis=(0, 1))

  # Apply game rules: birth, survival, death
  return (neighbors == 3) | ((neighbors == 2) & (world == 1))

# Example usage
world = np.random.randint(0, 2, size=(10, 10))  # Random initial world
n_steps = 10  # Number of steps to simulate

for _ in range(n_steps):
  world = conway_step(world)
  print(world)  # Print the world after each step



[[False False  True False False False False False  True  True]
 [False False  True False False False  True False  True  True]
 [False False False False False False  True False  True False]
 [False False False False False False False  True False False]
 [False False False False False False False  True False False]
 [ True False  True  True False False False False False  True]
 [False  True  True  True  True False False False False False]
 [False False False  True False  True False False False False]
 [False False  True False  True False False False False False]
 [False  True  True  True False False False False False  True]]
[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False Fals

No. 89

In [61]:
import numpy as np

def largest_n(arr, n):
  """
  Returns the n largest values of an array.

  Args:
    arr: A NumPy array.
    n: The number of largest values to return.

  Returns:
    A NumPy array containing the n largest values in descending order.
  """

  indices = np.argsort(arr)[-n:]  # Get indices of n largest elements in descending order
  return arr[indices]

# Example usage
arr = np.array([3, 5, 1, 8, 2, 4, 7, 6])
n = 3
largest_values = largest_n(arr, n)
print(largest_values)  # Output: [8 7 6]


[6 7 8]


No. 90

In [62]:
def cartesian_product(vectors):
  """
  Recursively builds the cartesian product of a list of vectors.

  Args:
    vectors: A list of vectors.

  Returns:
    A list of all elements in the cartesian product.
  """

  if not vectors:
    return [[]]  # Base case: empty list returns empty product

  first_vector, *rest_vectors = vectors
  product = []
  for element in first_vector:
    for sub_product in cartesian_product(rest_vectors):
      product.append([element] + sub_product)
  return product

# Example usage
vectors = [[1, 2], [3, 4], [5]]
product = cartesian_product(vectors)
print(product)  # Output: [[1, 3, 5], [1, 4, 5], [2, 3, 5], [2, 4, 5]]


[[1, 3, 5], [1, 4, 5], [2, 3, 5], [2, 4, 5]]


No. 91

In [ ]:
# Sample data as structured records
records = [
  {'name': "Alice", 'age': 25, 'height': 1.70},
  {'name': "Bob", 'age': 30, 'height': 1.85},
  {'name': "Charlie", 'age': 28, 'height': 1.78},
]

# Create record array
record_array = np.fromrecords(records, names=['name', 'age', 'height'])

# Accessing elements (similar to approach 1)
print(record_array[0].name)
print(record_array[1].age)
print(record_array['height'])


No. 92

In [65]:
import numpy as np

# Sample vector (adjust size as needed)
Z = np.random.rand(10000)

# Compute Z^3 using element-wise exponentiation
Z_cubed = Z**3

# Print the first few elements
print(Z_cubed[:5])


[0.7396736  0.50048968 0.61564187 0.05763374 0.37436741]


No. 93

In [ ]:
import numpy as np

# Sample arrays A and B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12],
             [13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]])
B = np.array([[2, 3], [1, 4]])

# Reshape B to have the same number of columns as A
B = B[:, np.newaxis, :]

# Check if each row of A contains all elements of any row of Bmatching_rows = np.where(np.any((A[..., np.newaxis, :] == B), axis=(3,1)))[0]

matching_rows = np.where(np.any((A[..., np.newaxis, :] == B), axis=(3,1)))[0]

# Print the matching rows
print("Matching rows in A:", matching_rows)


No. 94

In [71]:
import numpy as np

# Sample 10x3 matrix
matrix = np.random.randint(0, 10, size=(10, 3))

# Find rows with any unequal values
unequal_rows = np.where((matrix != matrix[:, np.newaxis, :]).any(axis=(1, 2)))[0]

# Extract and print the unequal rows
extracted_rows = matrix[unequal_rows]
print("Rows with unequal values:", extracted_rows)


Rows with unequal values: [[3 2 9]
 [0 1 9]
 [4 9 2]
 [1 8 4]
 [3 7 5]
 [1 6 4]
 [6 1 4]
 [0 1 6]
 [9 4 2]
 [0 6 6]]


No. 95

In [72]:
import numpy as np

# Sample vector of integers
vector = [3, 8, 15]

# Define desired width of binary representation (e.g., 8 bits)
width = 8

# Convert each integer to binary string and pad with zeros
binary_strings = np.array([f"{num:0{width}b}" for num in vector], dtype=str)

# Convert binary strings to a NumPy array of integers
binary_matrix = np.array([[int(bit) for bit in string] for string in binary_strings])

# Print the binary matrix
print(binary_matrix)


[[0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 1 1 1]]


No. 96

In [73]:
import numpy as np

# Sample 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9], [4, 5, 6]])

# Convert the array to a set of tuples (efficient for uniqueness checks)
unique_rows = set(tuple(row) for row in arr)

# Convert the set of tuples back to a NumPy array
unique_rows_array = np.array(list(unique_rows))

# Print the unique rows
print("Unique rows:")
print(unique_rows_array)


Unique rows:
[[7 8 9]
 [1 2 3]
 [4 5 6]]


No. 97

Inner product:

Incorrect: np.einsum('i,i->', A, B)
Correct: np.einsum('i,i->', A, B) or np.dot(A, B)
Both expressions are correct. The first uses einsum to sum over the same index in both vectors, achieving the same result as the standard np.dot function for inner product.

Outer product:

Correct: np.einsum('i,j->ij', A, B)
This expression creates a matrix where each element is the product of the corresponding elements from A and B.

Sum of elements:

Incorrect: np.einsum('i->', A) or np.einsum('->', A)
Correct: np.sum(A)
While both einsum expressions are technically valid, np.sum(A) is more straightforward and efficient for summing all elements of a vector.

Element-wise multiplication:

Incorrect: np.einsum('i,i->i', A, B)
Correct: np.einsum('i,i->i', A, B) or A * B

No. 98

In [74]:
import numpy as np

# Sample path coordinates
X = np.array([1, 3, 5, 7])
Y = np.array([2, 4, 6, 8])

# Number of desired samples
num_samples = 10

# Get distance between consecutive points
distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
total_distance = np.sum(distances)

# Sample positions along the path based on total distance
positions = np.linspace(0, total_distance, num_samples)

# Interpolate X and Y coordinates for each sample position
interp_x = np.interp(positions, np.cumsum(distances), X[:-1])
interp_y = np.interp(positions, np.cumsum(distances), Y[:-1])

# Append the last point to ensure equal sampling
interp_x = np.append(interp_x, X[-1])
interp_y = np.append(interp_y, Y[-1])

# Print the sampled points
print("Sampled points:")
print(np.stack((interp_x, interp_y), axis=1))


Sampled points:
[[1.         2.        ]
 [1.         2.        ]
 [1.         2.        ]
 [1.         2.        ]
 [1.66666667 2.66666667]
 [2.33333333 3.33333333]
 [3.         4.        ]
 [3.66666667 4.66666667]
 [4.33333333 5.33333333]
 [5.         6.        ]
 [7.         8.        ]]


No. 99

In [75]:
import numpy as np

def select_multinomial_draws(X, n):
  """
  Selects rows from X that represent draws from a multinomial distribution with n degrees.

  Args:
    X: A 2D NumPy array.
    n: The number of degrees in the multinomial distribution.

  Returns:
    A NumPy array containing the selected rows.
  """
  # Check if rows are integers, sum to n, and have positive values
  valid_rows = np.where((X.astype(int) == X) & (X.sum(axis=1) == n) & (X >= 0).all(axis=1))[0]
  return X[valid_rows]

# Example usage
X = np.array([[1, 2, 0], [2, 1, 3], [0, 0, 5]])
n = 5
selected_rows = select_multinomial_draws(X, n)
print("Selected rows:")
print(selected_rows)


Selected rows:
[[1 2 0]
 [2 1 3]
 [0 0 5]]


No. 100

In [76]:
import numpy as np

def bootstrap_conf_interval(X, num_samples=1000):
  """
  Computes bootstrapped 95% confidence intervals for the mean of an array.

  Args:
    X: A 1D NumPy array.
    num_samples: The number of bootstrap samples to draw.

  Returns:
    A tuple containing the lower and upper bound of the confidence interval.
  """

  # Sample with replacement and calculate means
  means = np.zeros(num_samples)
  for i in range(num_samples):
    sample = np.random.choice(X, size=len(X), replace=True)
    means[i] = sample.mean()

  # Sort the means and get percentiles for 95% confidence interval
  percentiles = np.percentile(means, [2.5, 97.5])
  return percentiles[0], percentiles[1]

# Example usage
X = np.random.rand(1000)  # Sample data
alpha = 0.05  # Confidence level (1 - alpha = 0.95)
lower_bound, upper_bound = bootstrap_conf_interval(X)

print("95% confidence interval for the mean:")
print(f"Lower bound: {lower_bound:.4f}, Upper bound: {upper_bound:.4f}")


95% confidence interval for the mean:
Lower bound: 0.4878, Upper bound: 0.5261
